; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = substation, powerplant

[env]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
board = ch32v003f4p6_evt_r0
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+
build_flags =
    -D CH32V003
lib_deps = 
    https://github.com/EnergetickaAkademie/PodSync
    https://github.com/EnergetickaAkademie/PeripheralsLib.git

[env:substation]
upload_protocol = wlink
monitor_speed = 9600
lib_ignore =
    Adafruit SSD1306
    Adafruit GFX Library
    Adafruit NeoPixel
build_src_filter =
    +<substation.cpp>
    #+<com-prot.cpp>
    -<powerplant.cpp>

[env:powerplant]
upload_protocol = wlink
lib_ignore =
    Adafruit SSD1306
    Adafruit GFX Library
    Adafruit NeoPixel
build_src_filter =
    +<powerplant.cpp>
    #+<com-prot.cpp>
    -<substation.cpp>


[env_mb]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_unflags =
    -Os

board_build.f_cpu = 240000000L
board_build.arduino.usb_mode = 1
board_build.arduino.usb_cdc_on_boot = 1

build_flags =
    -O2
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUHAL_LOG_COLORS=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -ffunction-sections
    -fdata-sections
    -fno-rtti
    -fno-exceptions

lib_deps = 
    https://github.com/EnergetickaAkademie/PeripheralsLib.git
    https://github.com/EnergetickaAkademie/PodSync
    https://github.com/EnergetickaAkademie/NFC-building-registry.git
    https://github.com/EnergetickaAkademie/ESP-API.git
    ayushsharma82/WebSerial@^1.4.0
    ottowinter/ESPAsyncWebServer-esphome@^3.0.0
    marian-craciunescu/ESP32Ping@^1.7
    https://github.com/igorantolic/ai-esp32-rotary-encoder.git
    https://github.com/EnergetickaAkademie/PN532


[env:mainboard]
extends = env_mb
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
build_src_filter =
    +<mainboard.cpp>
    +<GameState.cpp>
    +<NetworkManager.cpp>
    +<SubstationManager.cpp>
    -<substation.cpp>
    -<powerplant.cpp>
build_flags = 
    ${env_mb.build_flags}
