#ifndef BUILDING_TYPES_H
#define BUILDING_TYPES_H

#define BUILDING_CITY_CENTER			0
#define BUILDING_CITY_CENTER_A			1
#define BUILDING_CITY_CENTER_B			2
#define BUILDING_CITY_CENTER_C			3
#define BUILDING_CITY_CENTER_D			4
#define BUILDING_CITY_CENTER_E			5
#define BUILDING_CITY_CENTER_F			6
#define BUILDING_FACTORY				7
#define BUILDING_STADIUM				8
#define BUILDING_HOSPITAL				9
#define BUILDING_UNIVERSITY				10
#define BUILDING_AIRPORT				11
#define BUILDING_SHOPPING_MALL			12
#define BUILDING_TECHNOLOGY_CENTER		13
#define BUILDING_FARM					14
#define BUILDING_LIVING_QUARTER_SMALL	15
#define BUILDING_LIVING_QUARTER_LARGE	16
#define BUILDING_SCHOOL					17

#define BUILDING_COUNT 18

#endif