#include "DebugPortalHtml.h"

const char PORTAL_HTML[] PROGMEM = R"HTML(<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ENAK Debug Portal</title><style>
:root{font-family:'DINPro-Regular','Segoe UI',Arial,sans-serif;background:#f4f7fb;color:#243447}
*{box-sizing:border-box}body{max-width:1180px;margin:auto;padding:24px}h1{margin:8px 0 4px;font-size:clamp(30px,5vw,44px);font-weight:300;letter-spacing:-.02em}h2{margin:0;font-size:24px;font-weight:400}h3{margin:0;font-size:19px;font-weight:400}.subtitle{margin:0;color:#718096;font-size:16px}.eyebrow{margin:0 0 5px;color:#8494a6;font-size:11px;font-weight:700;letter-spacing:.12em}
.page-header{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;padding:24px 26px;background:#fff;border:1px solid #e3e8ef;border-radius:16px;box-shadow:0 5px 18px rgba(36,52,71,.07)}.brand{display:flex;align-items:center;gap:14px}.brand-mark{width:12px;height:52px;border-radius:7px;background:#27bd91}.page-header .subtitle{margin-top:8px}
section{margin-top:18px;padding:24px;background:#fff;border:1px solid #e3e8ef;border-radius:16px;box-shadow:0 5px 18px rgba(36,52,71,.07)}.section-heading{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:15px}label{display:block;margin:0 0 6px;color:#52708d;font-size:14px}input,select{width:100%;padding:11px 12px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;color:#243447;font:inherit;transition:border-color .2s,box-shadow .2s}input:focus,select:focus{outline:0;border-color:#5294cc;box-shadow:0 0 0 3px rgba(37,99,235,.12)}input::placeholder{color:#a0aec0}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px;padding-top:20px;border-top:1px solid #edf0f4}button{padding:11px 18px;border:0;border-radius:8px;background:#2563a6;color:#fff;font:inherit;font-weight:700;cursor:pointer;transition:background .2s,box-shadow .2s,transform .15s}button:hover{background:#1d4f82;box-shadow:0 5px 12px rgba(36,99,166,.2);transform:translateY(-1px)}button:disabled{opacity:.5;cursor:not-allowed;transform:none;box-shadow:none}button.secondary{background:#f1f5f9;color:#34536e}button.secondary:hover{background:#e2eaf2;box-shadow:none}.muted{color:#8494a6}.ok{color:#159447}.bad{color:#b91c1c}.message{min-height:1.3em;margin:14px 0 0;font-size:14px}.badge{padding:5px 9px;border-radius:999px;background:#eef4fa;color:#52708d;font-size:12px;font-weight:700}.badge.online{background:#e7f7ee;color:#159447}.badge.offline{background:#f1f5f9;color:#64748b}
.summary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:18px}.summary-card{display:flex;flex-direction:column;gap:4px;padding:15px 17px;background:#f8fafc;border-radius:10px;color:#718096}.summary-value{color:#243447;font-size:27px;font-weight:700}.summary-value.green{color:#159447}.topology{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.node{padding:17px;border:1px solid #e3e8ef;border-radius:12px;background:#fff}.node-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:12px}.last-seen{margin-bottom:12px;color:#8494a6;font-size:13px}.plant-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.plant{padding:7px 8px;border-radius:7px;background:#f1f5f9;color:#8494a6;font-size:12px}.plant.on{background:#e7f7ee;color:#159447;font-weight:700}
.nfc-toolbar{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.nfc-toolbar>div{flex:1;min-width:180px}.nfc-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.nfc-card{padding:16px;border:1px solid #e3e8ef;border-radius:12px;background:#f8fafc}.nfc-card h3{margin-bottom:10px}.nfc-value{font-family:monospace;font-size:30px;letter-spacing:3px;color:#243447}.nfc-bar{height:10px;border-radius:8px;background:#e2e8f0;overflow:hidden;margin:10px 0}.nfc-bar span{display:block;height:100%;background:#27bd91}.nfc-history{max-height:240px;overflow:auto;margin-top:12px}.nfc-event{display:flex;justify-content:space-between;gap:12px;padding:8px 0;border-bottom:1px solid #e8edf3;font-size:13px}.nfc-event small{color:#8494a6}.warning{padding:10px 12px;border-radius:8px;background:#fff4e5;color:#9a5b00;font-size:13px}.segment-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:10px}.segment{padding:12px;border-radius:10px;background:#243447;color:#f8fafc}.segment small{display:block;color:#a9bfd1;margin-bottom:4px}.segment strong{font-family:monospace;font-size:25px;letter-spacing:3px}
.encoder-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px}.encoder-card{padding:16px;border:1px solid #e3e8ef;border-radius:12px;background:#f8fafc}.encoder-card header{display:flex;justify-content:space-between;align-items:center}.encoder-card input[type=range]{padding:0;accent-color:#27bd91}.encoder-value{font-family:monospace;font-size:30px;letter-spacing:3px}.encoder-percent{color:#52708d;font-size:13px}.encoder-card input[type=number]{margin-top:8px}
@media(max-width:780px){body{padding:12px}.page-header{align-items:flex-start;flex-direction:column;padding:20px}.summary-grid,.topology{grid-template-columns:1fr}.actions button{flex:1}.plant-grid{grid-template-columns:repeat(2,1fr)}}
</style></head><body><header class="page-header"><div class="brand"><span class="brand-mark"></span><div><p class="eyebrow">ENAK MAINBOARD</p><h1>Debug portal</h1><p class="subtitle">Local configuration and hardware diagnostics</p></div></div><span class="badge">AP + STA</span></header>
<section><div class="section-heading"><div><p class="eyebrow">CONFIGURATION</p><h2>Board and network</h2></div><span class="badge">Reboot to apply</span></div><form id="config"><div class="grid">
<div><label>Board username</label><input id="board_username" required></div><div><label>Board password (blank = unchanged)</label><input id="board_password" type="password"></div><div><label>API endpoint</label><input id="api_base_url" required></div><div><label>Wi-Fi SSID</label><input id="wifi_ssid" required></div><div><label>Wi-Fi security</label><select id="wifi_security"><option value="1">WPA/WPA2 password</option><option value="0">Open network</option></select></div><div><label>Wi-Fi password (blank = unchanged)</label><input id="wifi_password" type="password"></div><div><label>OTA hostname</label><input id="ota_hostname" required></div><div><label>OTA port</label><input id="ota_port" type="number" min="1" max="65535" required></div><div><label>OTA password (blank = unchanged)</label><input id="ota_password" type="password"></div><div><label>Debug AP password (blank = unchanged)</label><input id="debug_ap_password" type="password" minlength="8" maxlength="63"></div>
</div><div class="actions"><button type="submit">Save and reboot</button><button type="button" class="secondary" id="exit">Exit without saving</button><button type="button" class="secondary" id="refresh">Refresh</button></div></form><p id="message" class="message muted"></p></section>
<section><div class="section-heading"><div><p class="eyebrow">FIRMWARE</p><h2>Stage a firmware update</h2><p class="subtitle">Upload a .bin file and optionally its .sha256 file, validate the image, and inspect its SHA-256 before selecting it for the next reboot.</p></div><span class="badge" id="firmware_badge">NOT STAGED</span></div><form id="firmware_form"><div class="nfc-toolbar"><div><label>Firmware image (.bin)</label><input id="firmware_file" type="file" accept=".bin,application/octet-stream" required></div><div><label>SHA-256 checksum (.sha256, optional)</label><input id="firmware_checksum" type="file" accept=".sha256,text/plain"></div><button type="submit">Upload and verify</button><button type="button" class="secondary" id="firmware_apply" disabled>Update firmware</button></div></form><div id="firmware_status" class="nfc-card" style="margin-top:14px">No verified firmware image is staged.</div></section>
<section><div class="section-heading"><div><p class="eyebrow">LIVE DIAGNOSTICS</p><h2>Connected hardware</h2></div><span class="badge online" id="updated">Updating</span></div><div id="summary" class="summary-grid"></div><div id="topology" class="topology"></div></section>
<section><div class="section-heading"><div><p class="eyebrow">NFC TOOLING</p><h2>Scanner and tag flasher</h2><p class="subtitle">Normal mode preserves the board workflow. Inspect shows every presented tag without side effects.</p></div><span class="badge" id="nfc_mode_badge">NORMAL</span></div><div class="nfc-toolbar"><div><label>Reader mode</label><select id="nfc_mode"><option value="normal">Normal</option><option value="inspect">Inspect only</option><option value="write">Write tags</option></select></div><div><label>Write profile</label><select id="nfc_profile_kind"><option value="building">Building</option><option value="reset">Building reset</option><option value="debug">Debug card</option><option value="wifi">Wi-Fi provisioning</option></select></div><div><label>Building type</label><select id="nfc_building_type"></select></div><button type="button" id="nfc_profile_save">Use profile</button><button type="button" id="nfc_arm" class="secondary">Arm continuous writing</button></div><div id="nfc_wifi_fields" class="grid" style="margin-top:14px;display:none"><div><label>Wi-Fi SSID</label><input id="nfc_wifi_ssid" maxlength="32"></div><div><label>Security</label><select id="nfc_wifi_security"><option value="1">WPA/WPA2 password</option><option value="0">Open network</option></select></div><div><label>Password</label><input id="nfc_wifi_password" type="password" maxlength="63"></div></div><p class="warning" style="margin-top:14px">Write mode overwrites writable NDEF contents. Keep the tag on the reader only long enough for one operation; remove it before presenting the next tag.</p><div id="nfc_current" class="nfc-card" style="margin-top:14px">No tag has been presented.</div><div class="summary-grid" style="margin-top:14px"><div class="summary-card"><span class="summary-value" id="nfc_success">0</span><span>Successful operations</span></div><div class="summary-card"><span class="summary-value" id="nfc_failure">0</span><span>Failed operations</span></div><div class="summary-card"><span class="summary-value" id="nfc_armed">OFF</span><span>Writer state</span></div></div><div id="nfc_history" class="nfc-history"></div></section>
<section><div class="section-heading"><div><p class="eyebrow">BUILDING INVENTORY</p><h2>Scanned buildings</h2><p class="subtitle">Remove a building to decrement its server total and allow its tag to be scanned again later.</p></div><span class="badge" id="building_count">0 SCANNED</span></div><div id="building_inventory" class="nfc-history">No buildings have been scanned in this scenario.</div></section>
<section><div class="section-heading"><div><p class="eyebrow">ENCODER CONTROLS</p><h2>Live board inputs</h2><p class="subtitle">Changes are temporary and use the same live values as the physical knobs.</p></div></div><div id="encoders" class="encoder-grid"></div></section>
<section><div class="section-heading"><div><p class="eyebrow">PHYSICAL OUTPUTS</p><h2>Seven-segment displays</h2></div></div><div id="segments" class="segment-grid"></div></section>
<script>
const token='__TOKEN__', names=['Solar','Wind','Nuclear','Gas','Hydro','Pumped storage','Coal','Battery'];
const buildingNames=['City center','City center A','City center B','City center C','City center D','City center E','City center F','Factory','Stadium','Hospital','University','Airport','Shopping mall','Technology center','Farm','Small living quarter','Large living quarter','School'];
const byId=id=>document.getElementById(id); function setValue(id,v){byId(id).value=v??''}
async function loadConfig(){const r=await fetch('/api/config',{cache:'no-store'});if(!r.ok)throw Error('Configuration read failed');const c=await r.json();setValue('board_username',c.board_username);setValue('api_base_url',c.api_base_url);setValue('wifi_ssid',c.wifi_ssid);setValue('wifi_security',c.wifi_security);setValue('ota_hostname',c.ota_hostname);setValue('ota_port',c.ota_port);byId('wifi_password').placeholder=c.wifi_password_set?'Stored password':'Required';byId('board_password').placeholder=c.board_password_set?'Stored password':'Required';byId('ota_password').placeholder=c.ota_password_set?'Stored password':'Required';byId('debug_ap_password').placeholder=c.debug_ap_password_set?'Stored password':'enak-debug'}
function showMessage(t,bad=false){byId('message').textContent=t;byId('message').className='message '+(bad?'bad':'ok')}
function renderSegments(d){byId('segments').innerHTML=(d.displays||[]).map(x=>'<div class="segment"><small>'+x.label+'</small><strong>'+(x.visible?String(x.value).padStart(4,' '):'----')+'</strong></div>').join('')}
const encoderTimers={};
function queueEncoder(index,value){clearTimeout(encoderTimers[index]);encoderTimers[index]=setTimeout(async()=>{try{await nfcPost('/api/encoder',{index:index,value_mw:Number(value)})}catch(x){showMessage(x.message,true)}},120)}
function renderEncoders(list){const root=byId('encoders');if(!list.length){root.innerHTML='<div class="muted">Encoder data is not available yet.</div>';return}if(root.children.length!==list.length){root.innerHTML=list.map((x,i)=>'<div class="encoder-card"><header><h3>'+x.label+'</h3><span class="encoder-percent" id="encoder_pct_'+i+'">0%</span></header><div class="encoder-value" id="encoder_value_'+i+'">0000</div><input type="range" id="encoder_range_'+i+'" step="1" oninput="encoderInput('+i+',this.value)"><input type="number" id="encoder_number_'+i+'" oninput="encoderInput('+i+',this.value)"><small class="muted" id="encoder_range_text_'+i+'"></small></div>').join('')}list.forEach((x,i)=>{const range=byId('encoder_range_'+i),number=byId('encoder_number_'+i);range.min=x.minimum_mw;range.max=Math.max(x.maximum_mw,x.minimum_mw);range.disabled=x.maximum_mw<=x.minimum_mw;number.min=x.minimum_mw;number.max=x.maximum_mw;number.disabled=x.maximum_mw<=x.minimum_mw;if(document.activeElement!==range&&document.activeElement!==number){range.value=x.value_mw;number.value=x.value_mw}byId('encoder_value_'+i).textContent=String(x.value_mw).padStart(4,' ');byId('encoder_pct_'+i).textContent=Math.round((x.percentage||0)*100)+'%';byId('encoder_range_text_'+i).textContent=x.minimum_mw+'–'+x.maximum_mw+' MW'})}
function encoderInput(index,value){const range=byId('encoder_range_'+index),number=byId('encoder_number_'+index);const v=Number(value);if(!Number.isFinite(v))return;range.value=v;number.value=v;byId('encoder_value_'+index).textContent=String(v).padStart(4,' ');queueEncoder(index,v)}
async function loadStatus(){const s=await (await fetch('/api/status',{cache:'no-store'})).json();byId('summary').innerHTML='<div class="summary-card"><span class="summary-value">'+s.board_name+'</span><span>Board</span></div><div class="summary-card"><span class="summary-value">'+s.firmware_version+'</span><span>Firmware</span></div><div class="summary-card"><span class="summary-value green">'+s.online_substations+' / 3</span><span>Substations online</span></div>';byId('topology').innerHTML=s.substations.map((x,i)=>'<div class="node"><div class="node-head"><h3>Substation '+(i+1)+'</h3><span class="badge '+(x.online?'online':'offline')+'">'+(x.online?'ONLINE':'OFFLINE')+'</span></div><div class="last-seen">'+(x.online?'Last seen '+x.last_seen_age_ms+' ms ago':'No recent heartbeat')+'</div><div class="plant-grid">'+x.plants.map((n,j)=>'<span class="plant '+(n?'on':'')+'">'+names[j]+' &middot; '+n+'</span>').join('')+'</div></div>').join('');renderSegments(s);renderEncoders(s.encoders||[]);byId('updated').textContent='Updated now'}
function applyNfcProfile(profile){byId('nfc_profile_kind').value=profile.kind||'building';byId('nfc_building_type').value=profile.building_type??0;byId('nfc_wifi_ssid').value=profile.wifi_ssid||'';byId('nfc_wifi_security').value=profile.wifi_security??1}
function renderNfc(s,syncProfile=false){byId('nfc_mode').value=s.mode;if(syncProfile&&s.profile)applyNfcProfile(s.profile);updateNfcFields();byId('nfc_mode_badge').textContent=s.mode.toUpperCase()+(s.armed?' · ARMED':'');byId('nfc_armed').textContent=s.armed?'ON':'OFF';byId('nfc_success').textContent=s.success_count;byId('nfc_failure').textContent=s.failure_count;const t=s.current_tag;byId('nfc_current').innerHTML=t?'<b>'+(t.write?'Write':'Scan')+' '+(t.success?'succeeded':'failed')+'</b><br>UID '+t.uid+' · '+t.technology+'<br>'+t.record_type+' · '+t.protocol+(t.building_type<18?' · '+buildingNames[t.building_type]:'')+'<br><small>'+t.detail+' · '+t.age_ms+' ms ago</small>':'No tag has been presented.';byId('nfc_history').innerHTML=(s.history||[]).slice().reverse().map(t=>'<div class="nfc-event"><span>'+t.uid+' · '+(t.record_type||'Unknown')+'<br><small>'+t.detail+'</small></span><span class="'+(t.success?'ok':'bad')+'">'+(t.success?'OK':'FAIL')+'</span></div>').join('')}
async function loadNfc(syncProfile=false){const r=await fetch('/api/nfc/status',{cache:'no-store',headers:{'X-Debug-Token':token}});if(r.ok)renderNfc(await r.json(),syncProfile)}
async function nfcPost(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Debug-Token':token},body:JSON.stringify(data||{})});const x=await r.json();if(!r.ok)throw Error(x.error||'NFC request failed');return x}
function escapeHtml(value){return String(value??'').replace(/[&<>\"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x]))}
function renderBuildings(list){const root=byId('building_inventory');byId('building_count').textContent=list.length+' SCANNED';if(!list.length){root.textContent='No buildings have been scanned in this scenario.';return}root.innerHTML=list.map(x=>{const type=Number(x.building_type),name=buildingNames[type]||'Unknown';const uid=String(x.uid??'');return '<div class="nfc-event"><span><b>'+escapeHtml(uid)+'</b><br><small>'+escapeHtml(name)+' · 0x'+type.toString(16).padStart(2,'0').toUpperCase()+'</small></span><button type="button" class="secondary" data-building-uid="'+encodeURIComponent(uid)+'">Remove</button></div>'}).join('')}
async function loadBuildings(){const r=await fetch('/api/buildings',{cache:'no-store',headers:{'X-Debug-Token':token}});if(!r.ok)throw Error('Building inventory read failed');const x=await r.json();renderBuildings(x.buildings||[])}
byId('building_inventory').onclick=async e=>{const button=e.target.closest('button[data-building-uid]');if(!button)return;const uid=decodeURIComponent(button.dataset.buildingUid);if(!confirm('Remove building '+uid+' from the server total and local scan list?'))return;button.disabled=true;try{await nfcPost('/api/buildings/remove',{uid:uid});showMessage('Building removed. It can be scanned again.');await loadBuildings()}catch(x){showMessage(x.message,true);button.disabled=false}}
function updateNfcFields(){const write=byId('nfc_mode').value==='write',kind=byId('nfc_profile_kind').value;byId('nfc_profile_kind').parentElement.style.display=write?'block':'none';byId('nfc_wifi_fields').style.display=write&&kind==='wifi'?'grid':'none';byId('nfc_building_type').parentElement.style.display=write&&kind==='building'?'block':'none';byId('nfc_profile_save').style.display='none';byId('nfc_arm').style.display=write?'inline-block':'none';const warning=document.querySelector('.warning');if(warning)warning.style.display=write?'block':'none'}
async function autoApplyNfcProfile(){const kind=byId('nfc_profile_kind').value;const ssid=byId('nfc_wifi_ssid').value;const security=Number(byId('nfc_wifi_security').value);const password=byId('nfc_wifi_password').value;if(kind==='wifi'&&(ssid.length===0||ssid.length>32||security===1&&(password.length<8||password.length>63)||security===0&&password.length!==0)){showMessage('Complete the Wi-Fi profile before applying it.',true);return}const data={kind:kind,building_type:Number(byId('nfc_building_type').value),wifi_ssid:ssid,wifi_security:security,wifi_password:password};try{await nfcPost('/api/nfc/profile',data);showMessage('NFC write profile selected');await loadNfc(true)}catch(x){showMessage(x.message,true)}}
['nfc_wifi_ssid','nfc_wifi_security','nfc_wifi_password'].forEach(id=>byId(id).onchange=autoApplyNfcProfile);
buildingNames.forEach((n,i)=>{const o=document.createElement('option');o.value=i;o.textContent=n+' (0x'+i.toString(16).padStart(2,'0').toUpperCase()+')';byId('nfc_building_type').appendChild(o)});updateNfcFields();byId('nfc_profile_kind').onchange=()=>{updateNfcFields();autoApplyNfcProfile()};byId('nfc_building_type').onchange=autoApplyNfcProfile;
byId('nfc_mode').onchange=async()=>{try{await nfcPost('/api/nfc/mode',{mode:byId('nfc_mode').value});await loadNfc(true)}catch(x){showMessage(x.message,true)}};byId('nfc_profile_save').onclick=async()=>{const data={kind:byId('nfc_profile_kind').value,building_type:Number(byId('nfc_building_type').value),wifi_ssid:byId('nfc_wifi_ssid').value,wifi_security:Number(byId('nfc_wifi_security').value),wifi_password:byId('nfc_wifi_password').value};try{await nfcPost('/api/nfc/profile',data);showMessage('NFC write profile selected');await loadNfc(true)}catch(x){showMessage(x.message,true)}};byId('nfc_arm').onclick=async()=>{try{const armed=byId('nfc_armed').textContent!=='ON';await nfcPost('/api/nfc/arm',{armed:armed});await loadNfc()}catch(x){showMessage(x.message,true)}};
function renderFirmware(s){const ready=Boolean(s.ready),badge=byId('firmware_badge'),apply=byId('firmware_apply');badge.textContent=ready?'VERIFIED':'NOT STAGED';badge.className='badge '+(ready?'online':'');apply.disabled=!ready;if(ready){byId('firmware_status').textContent='Verified '+s.filename+' · '+s.size+' bytes · SHA-256 '+s.sha256+(s.hash_provided?(s.hash_matched?' · checksum matched':' · checksum mismatch'):' · checksum not supplied')}else{byId('firmware_status').textContent=s.error||'No verified firmware image is staged.'}}
async function loadFirmwareStatus(){const r=await fetch('/api/firmware/status',{cache:'no-store',headers:{'X-Debug-Token':token}});if(!r.ok)throw Error('Firmware status read failed');renderFirmware(await r.json())}
byId('firmware_form').addEventListener('submit',async e=>{e.preventDefault();const file=byId('firmware_file').files[0],checksum=byId('firmware_checksum').files[0],submit=e.submitter||byId('firmware_form').querySelector('button[type="submit"]');if(!file||!file.name.toLowerCase().endsWith('.bin')){showMessage('Choose a .bin firmware image.',true);return}if(checksum&&!checksum.name.toLowerCase().endsWith('.sha256')){showMessage('The checksum file must use the .sha256 extension.',true);return}submit.disabled=true;showMessage('Uploading, validating, and checking SHA-256…');const data=new FormData();data.append('firmware',file,file.name);if(checksum)data.append('checksum',checksum,checksum.name);try{const r=await fetch('/api/firmware/upload',{method:'POST',headers:{'X-Debug-Token':token},body:data});const x=await r.json();if(!r.ok)throw Error(x.error||'Firmware upload failed');renderFirmware(x);showMessage(x.hash_matched?'Firmware uploaded, verified, and checksum matched.':'Firmware uploaded and verified.')}catch(x){showMessage(x.message,true);loadFirmwareStatus().catch(()=>{})}finally{submit.disabled=false}});
byId('firmware_apply').onclick=async()=>{if(!confirm('Select the verified firmware for the next reboot?'))return;byId('firmware_apply').disabled=true;try{const r=await fetch('/api/firmware/update',{method:'POST',headers:{'X-Debug-Token':token}});const x=await r.json();if(!r.ok)throw Error(x.error||'Firmware update failed');showMessage('Firmware selected. Rebooting…')}catch(x){showMessage(x.message,true);loadFirmwareStatus().catch(()=>{})}};
byId('config').addEventListener('submit',async e=>{e.preventDefault();const data={};['board_username','board_password','api_base_url','wifi_ssid','wifi_password','ota_hostname','ota_password','debug_ap_password'].forEach(k=>data[k]=byId(k).value);data.wifi_security=Number(byId('wifi_security').value);data.ota_port=Number(byId('ota_port').value);showMessage('Saving…');try{const r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json','X-Debug-Token':token},body:JSON.stringify(data)});const x=await r.json();if(!r.ok)throw Error(x.error||'Save failed');showMessage('Saved. Rebooting into normal mode…')}catch(x){showMessage(x.message,true)}});byId('exit').onclick=async()=>{if(!confirm('Exit debug mode?'))return;await fetch('/api/exit',{method:'POST',headers:{'X-Debug-Token':token}});showMessage('Debug mode stopped. Returning to normal operation…')};byId('refresh').onclick=()=>{loadConfig().catch(x=>showMessage(x.message,true));loadStatus().catch(x=>showMessage(x.message,true));loadNfc(true).catch(x=>showMessage(x.message,true));loadFirmwareStatus().catch(x=>showMessage(x.message,true));loadBuildings().catch(x=>showMessage(x.message,true))};loadConfig().catch(x=>showMessage(x.message,true));loadStatus().catch(x=>showMessage(x.message,true));loadNfc(true).catch(x=>showMessage(x.message,true));loadFirmwareStatus().catch(x=>showMessage(x.message,true));loadBuildings().catch(x=>showMessage(x.message,true));setInterval(()=>{loadStatus().catch(()=>{});loadNfc().catch(()=>{});loadFirmwareStatus().catch(()=>{});loadBuildings().catch(()=>{})},1000);
</script></body></html>)HTML";
